//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Runner.rc
//
#define IDOK2                           2
#define IDC_ABORT                       3
#define IDC_IGNORE                      4
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMVIEW                    101
#define IDD_RUNNER_DIALOG               102
#define IDD_RUNNER_FORM                 102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDP_RUN_DATA					104
#define IDR_MAINFRAME_                  128
#define IDD_RUNNER_LOAD                 129
#define IDD_RUNNER_LOGO                 130
#define IDD_DIALOG1                     131
#define IDR_MAIN_MENU                   132
#define IDR_TOOLBAR                     133
#define IDR_GIF1                        135
#define IDR_GIF2                        136
#define IDR_GIF3                        137
#define IDR_GIF4                        138
#define IDR_GIF5                        139
#define IDR_GIF6                        140
#define IDR_GIF7                        141
#define IDR_GIF8                        142
#define IDR_GIF9                        143
#define IDR_GIF10                       144
#define IDR_GIF11                       145
#define IDR_GIF12                       146
#define IDR_GIF13                       147
#define IDR_GIF14                       148
#define IDR_GIF15                       149
#define IDR_MAINFRAME                   152
#define IDR_BACKIMAGE                   156
#define IDB_BITMAP3                     158
#define IDB_BITMAP4                     159
#define IDB_BITMAP5                     160
#define IDB_BITBTN                      165
#define IDD_RUN_SCORE                   173
#define IDB_HICOLOR_TOOLBAR_DISABLED    176
#define IDB_HICOLOR_TOOLBAR_HOT         177
#define IDB_HICOLOR_TOOLBAR             178
#define IDD_DEBUGINFO_DIALOG            179
#define IDD_HELP2                       188
#define IDD_HELP                        188
#define IDD_DIALOG2                     192
#define IDC_EDIT1                       1001
#define IDC_ERROR_TEXT                  1001
#define IDC_LOADIMAGE                   1006
#define IDC_LOADLABEL                   1007
#define IDC_LOADFULLSHAPE               1008
#define IDC_DEBUG_VALUES_LIST           1008
#define IDC_EMPTYSHAPE                  1009
#define IDC_INFOEDIT                    1020
#define IDC_RUNNER_REPORT               1020
#define IDD_DEBUGFORM_DIALOG            1021
#define IDC_INFOICON                    1022
#define IDC_CLOSELABEL                  1023
#define IDC_RANK1                       1024
#define IDC_RANK2                       1025
#define IDC_RANK3                       1026
#define IDC_RANK4                       1027
#define IDC_RANK5                       1028
#define IDC_RANK6                       1029
#define IDC_RANK7                       1030
#define IDC_RANK8                       1031
#define IDC_RANK9                       1032
#define IDC_RANK10                      1033
#define IDC_NAME1                       1034
#define IDC_NAME2                       1035
#define IDC_NAME3                       1036
#define IDC_NAME4                       1037
#define IDC_NAME5                       1038
#define IDC_NAME6                       1039
#define IDC_NAME7                       1040
#define IDC_NAME8                       1041
#define IDC_NAME9                       1042
#define IDC_NAME10                      1043
#define IDC_SCORE1                      1044
#define IDC_SCORE2                      1045
#define IDC_SCORE3                      1046
#define IDC_SCORE4                      1047
#define IDC_SCORE5                      1048
#define IDC_SCORE6                      1049
#define IDC_SCORE7                      1050
#define IDC_SCORE8                      1051
#define IDC_SCORE9                      1052
#define IDC_SCORE10                     1053
#define IDC_PROMPT                      1055
#define IDC_LIST1                       1059
#define IDC_DEBUG_LIST_BOX              1059
#define IDC_LIST2                       1060
#define IDC_EDITBOX                     1061
#define IDC_DEBUG_FPS                   1062
#define IDC_LOGIN_PASSWORD              1062
#define IDC_DEBUG_INST                  1063
#define IDC_COPY                        1063
#define IDC_DEBUG_MOUSEID               1064
#define IDC_CLEAR                       1064
#define QUESTION_IDOK                   1066
#define QUESTION_IDCANCEL               1067
#define QUESTION_IDC_PROMPT             1068
#define QUESTION_IDC_PROMPT2            1069
#define IDC_LOGIN_USERNAME              1070
#define IDC_INSTANCE_SPRITENAME_LIST_BOX 1074
#define IDC_INSTANCE_ID_LIST_BOX        1075
#define IDC_INSTANCE_OBJECTNAME_LIST_BOX 1076
#define IDC_MESSAGE_LIST_BOX            1077
#define IDC_LOCALS_LIST_BOX1            1078
#define IDC_LOCALS_LIST_BOX2            1079
#define IDC_ROOM_FPS                    1080
#define IDC_DISPLAY_FPS_CHECK           1081
#define IDC_NUM_VERTEX_BATCHES          1082
#define IDC_NUM_TEX_SWAPS               1083
#define IDC_MESSAGE_STATIC              1084
#define ID_RUN_RUN                      32771
#define ID_RUN_PAUSE                    32772
#define ID_RUN_STEP                     32773
#define ID_RUN_RESTART                  32774
#define ID_RUN_STOP                     32775
#define ID_WATCH_ADD                    32776
#define ID_WATCH_DELETE                 32777
#define ID_WATCH_CLEAR                  32778
#define ID_WATCH_CHANGE                 32779
#define ID_WATCH_DELETE32780            32780
#define ID_WATCH_CLEAR32781             32781
#define ID_WATCH_LOAD                   32782
#define ID_WATCH_SAVE                   32783
#define ID_TOOLS_EXECUTECODE            32784
#define ID_TOOLS_SETSPEED               32785
#define ID_TOOLS_SHOWGLOBALVARIABLES    32786
#define ID_TOOLS_SHOWLOCALVARIABLES     32787
#define ID_TOOLS_SHOWINSTANCES          32788
#define ID_TOOLS_SHOWMESSAGES           32789
#define ID_BUTTON_PLAY                  32790
#define ID_BUTTON_PAUSE                 32791
#define ID_BUTTON_STEP                  32792
#define ID_BUTTON_RESTART               32793
#define ID_BUTTON_STOP                  32794
#define ID_BUTTON_ADD                   32795
#define ID_BUTTON_CHANGE                32796
#define ID_BUTTON_DELETE                32797
#define ID_BUTTON_DELETEALL             32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
